FROM debian:stable-slim

RUN mkdir -p /app/config \
  && adduser --disabled-password --gecos "" --home /app --no-create-home -u 5000 app \
  && apt-get update \
  && apt-get install -y gnupg2 ca-certificates \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/

COPY target/release/statics /app
COPY config /app/config

RUN chown -R app: /app

ENV PATH=$PATH:/usr/local/cargo/bin/
EXPOSE 8000
WORKDIR /app
USER app

ENTRYPOINT ["/app/statics"]
