[jwt]
public_key_path = "config/keys/public_key.der"
leeway = 86400

[S3]
bucket = "storiqa-dev"
key = "AKIAJTQ4IR33MOO6VS2Q"
secret = "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"

[graylog]
addr = "udplog.stq.cloud:32303"
